version: "3.4"

services:
  myapp:
    image: myapp
    container_name: myapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - APP_ENV=production
